# Generated by Django 3.1.4 on 2020-12-20 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todos',
            old_name='title',
            new_name='titlee',
        ),
    ]
